### ISSUE TITLE
How to make api requests to our own apis from within admin bro?

### ISSUE THREAD

**Issue by kiminohero** [SoftwareBrothers/admin-bro#269]

**Comment by wojtek-krysiak** [comment]
2 ways depending on what you want to do.

1. If you want to have a resource on the sidebar which (instead of talking to the database) fetches data from your API. In this case, you will have to implement your own class which extends [BaseResource](https://softwarebrothers.github.io/admin-bro-dev/BaseResource.html) and gives this class to the AdminBroSettings in resources [section](https://softwarebrothers.github.io/admin-bro-dev/AdminBroOptions.html#resources). It is not well documented way but you can take a look at this old example: https://github.com/SoftwareBrothers/admin-bro-example-app/blob/f77d1f9eb7f03a5e1225409ee1d5dd663570c8c4/rest/postcode.js

2. If you just want to fetch data from the API in your custom components: then you can use axios (import axios from "axios").

**Comment by kiminohero** [comment]
Thanks for the quick response. But I am trying to download a certain file from the server by making an API request which uses res.download(<filepath>) to do so. How do I do this?
