### ISSUE TITLE
Hide resource array object

### ISSUE THREAD

**Issue by lavanphat** [SoftwareBrothers/admin-bro#288]
I have array of objects
![image](https://user-images.githubusercontent.com/45566810/74085790-73c14680-4aaf-11ea-9c00-ef7784288791.png)
When clicking on add new
![image](https://user-images.githubusercontent.com/45566810/74085825-bdaa2c80-4aaf-11ea-9fed-15ce8c01e5fe.png)
I want to hide the ID fields and replace the link fields with file uploads. what should I do

**Comment by wojtek-krysiak** [comment]
assuming you use mongoose with nested schemas - it that's the case you can use {_id: false} option when defining schema.

Take a look at the example from our "example app":

https://github.com/SoftwareBrothers/admin-bro-example-app/blob/a839c61dbf4d291edfe35e06b028bc6bb4680489/mongoose/complicated-model.js#L17

Regarding file upload.
I would suggest to use our latest beta 2.0 version because we are rewriting entire UI and it is not backwards compatible :(
2.0 example: https://admin-bro-example-app-staging.herokuapp.com/admin

In 2.0 there is a DropZone component which you can use.

https://softwarebrothers.github.io/admin-bro-dev/v2/DropZone.html

On the backend you will need to override before/after hooks to either store uploaded file in hdd or upload it somewhere (aws s3 etc).

**Comment by wojtek-krysiak** [comment]
PS: 2.0 hides these ID fields by default
