### ISSUE TITLE
BaseDatabase.resources() should be async 

### ISSUE THREAD

**Issue by KrishnaPG** [SoftwareBrothers/admin-bro#467]
**Describe the problem feature solves**
Currently `BaseDatabase` gathers the resources in a synchronous fashion. But many databases list their collections in an asynchronous fashion.  This makes it difficult to create adapters for them.

**Describe the solution you'd like**
The `resources()` method should be invoked asynchronously and should allow returning a promise.
https://github.com/SoftwareBrothers/admin-bro/blob/48bedb53ad45b3ca06bded388d0bf41347f487b1/src/backend/adapters/base-database.ts#L37

**Comment by wojtek-krysiak** [comment]
@KrishnaPG I just sat on that and unfortunately decided that we won't merge it to the core. But I have good news for you (read more)

This is why:
Currently, all the schema building is done in the constructor of AdminBro. So when users run `new AdminBro` and pass their resources - admin builds the schema once. So in order to implement this would be to add some additional method `async admin#initialize` which will have to be run after new (since constructor cannot by async). This will make the panel more complicated to use.

But the solution would be to create som factory function, which can be async, which will return BaseDatabase like this:

```
const { buildAdapter } = require('path to your adapter')

const run = async () => {
   const adapter = await buildAdapter()
   AdminBro.registerAdapter(adapter)
   
   const admin = new AdminBro({ databases: [yourDb]})
   // other adminbro/express setup
}

run()

```
