### ISSUE TITLE
ResourceDecorator.getResourceName() is not using the resource name

### ISSUE THREAD

**Issue by KrishnaPG** [SoftwareBrothers/admin-bro#471]
**Describe the bug**
Resources in the sidebar are always showing `id` and not `name`. The `name()` method is never being called on the resource extended from `BaseResource`. 

**Installed libraries and their versions**

    "admin-bro": "^2.4.2",
    "admin-bro-expressjs": "^2.0.5",
    "admin-bro-sequelizejs": "^0.4.4",

**To Reproduce**
Implement a custom resource that has different `name` and `id` values. 
````
class Resource extends BaseResource {
	name() {
		return this.model.name;	// table name
	}

	id() {
		return `${this.model.migId}-${this.model.name}`;
	}

}
````
You would see only `id()` method being called, and never the `name()` method on the resource.

**Expected behavior**
`name()` method should be called on the resource and used in the sidebar.

**Screenshots**
Refer to the sidebar produced (the bug):
![image](https://user-images.githubusercontent.com/4610831/83416096-c7c8b000-a43d-11ea-9d86-95dbdea3c310.png)

What it **should** look like (after the fixing the issue)

![image](https://user-images.githubusercontent.com/4610831/83416228-02324d00-a43e-11ea-9127-69947fefa56c.png)

--------------
**Fix / Solution**

The problem is in the below code https://github.com/SoftwareBrothers/admin-bro/blob/6551b2b60c05f0f6c330bfd4a9d872573b2f9d13/src/backend/decorators/resource-decorator.ts#L157-L160

Note that in the current code both parameters are being sent as `id()`. The first parameter should be resource name, as shown below, which **fixes** the problem:
````
  getResourceName() {
    return this._admin.translateLabel(this._resource.name(), this.id());
  }
````

**Comment by leibowitz** [comment]
Everything can pretty much be translate in admin-bro. Including resource names. I guess that is why it is using the id rather than the name.

If you wish to change the name of the resource in the sidebar, set the name via the labels property on the [`AdminBroOptions`](https://adminbro.com/AdminBroOptions.html#LocaleTranslations)

**Comment by KrishnaPG** [comment]
That does not fix the bug with the `getResourceName` method. It should be returning a `name` not `id`.  Check out the buggy code here - `name` is not being used at all.

https://github.com/SoftwareBrothers/admin-bro/blob/6551b2b60c05f0f6c330bfd4a9d872573b2f9d13/src/backend/decorators/resource-decorator.ts#L157-L160

This is the **fix for the bug** 

````
  getResourceName() {
    return this._admin.translateLabel(this._resource.name(), this.id());
  }
````

**Comment by leibowitz** [comment]
For both [sequelizejs](https://github.com/SoftwareBrothers/admin-bro-sequelizejs/blob/74776c4a04a09022e29610b0729bc2b7694b0b0c/src/resource.js#L38-L44) and [mongoose](https://github.com/SoftwareBrothers/admin-bro-mongoose/blob/master/src/resource.js#L53-L59), `id` and `name` are essentially returning the same (tableName). 

But I get now what you mean, in a custom adaptor where the `name` and `id` func is returning something different. I think your suggestion would work, but the other way around:
```
  getResourceName() {
    return this._admin.translateLabel(this.id(), this._resource.name());
  }
```

Since the [`id` property can be customised](https://github.com/SoftwareBrothers/admin-bro/blob/def12a492082d50a1220c90d17f4c6cd7a70e92d/src/backend/decorators/resource-decorator.ts#L165-L167), when using multiple resources with the same table name, for instance

**Comment by wojtek-krysiak** [comment]
originally BaseResource#name meant to return the human-readable name for a table. But along the way, we introduced i18n which moves all the human-readable things to AdminBroOptions.locale option. That is why BaseResource#name will be deprecated soon (as you pointed out it is not invoked anywhere).
