### ISSUE TITLE
Can Not Post Any Data From Panel

### ISSUE THREAD

**Issue by aminahmadydeveloper** [SoftwareBrothers/admin-bro#593]
**Describe the bug**
hi every body, my admin panel has set up successful and working fine BUT i cant post any data from my panel but its OK with postman
 on panel error: There was an error updating record, Check out console to see more information.
AND no log in console!

**Installed libraries and their versions**

"@admin-bro/express": "^3.0.0",
    "@admin-bro/mongoose": "^1.0.0",
    "admin-bro": "^3.2.5",
    "admin-bro-theme-dark": "^1.0.0",
    "body-parser": "^1.19.0",
    "express": "^4.17.1",
    "express-formidable": "^1.2.0",
    "mongoose": "^5.10.4",
    "morgan": "^1.10.0",
    "nodemon": "^2.0.4"

**My POST Req Source**
```
router.post('/' ,(req, res, next) => {
    const product = new Product({
        _id: new mongoose.Types.ObjectId(),
        name: req.body.name,
        description: req.body.description,
        price: req.body.price,
        perviousPrice: req.body.perviousPrice,
        inStock: req.body.inStock,
    })

    product
    .save()
    .then(result => console.log(result))
    .catch(error => console.log(error))


    res.status(201).json({
        Created: product
        })
})

```

help me with this
thanks you

**Comment by wojtek-krysiak** [comment]
Info: admin uses formidable to parse the incoming data (we are sending it via FormData - not via application JSON, due to the fact that we have to be able to send Files).

And some other express middleware also parses the incoming data and brakes AdminBro (body parser is the most often a problem). So this is what I suggest

Turn off all your other routes temporarily and see if (when left alone) AdminBro works fine with POST. If that is the case, move AdminBro initialization on the top of the file (as the first middleware) and turn off other middleware.

You can gradually turn on middleware as well and let me know which happened to be an issue. I will add some message to the core as we did with body parser: https://github.com/SoftwareBrothers/admin-bro-expressjs/blob/948b0b78841aebfd207eb68cee2e43cb6e6c3147/plugin.js#L157-L171

**Comment by aminahmadydeveloper** [comment]
thanks very much.
all of my middlewares are deactive
so there is nothing wrong between middlewares

and when i check console there is an error in network section witch i forgot to check yesterday:


admin bro req is :
```
-----------------------------188910956530102845323742406638
Content-Disposition: form-data; name="name"

test
-----------------------------188910956530102845323742406638
Content-Disposition: form-data; name="price"

12
-----------------------------188910956530102845323742406638--
```


and server res is 
```
MongooseError: document must have an _id before saving
    at Timeout._onTimeout (D:\Work Space\ExpressJS\RESTful Store API\node_modules\mongoose\lib\model.js:269:18)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
```

it seems admin bro does not generate _id using mongoose

thank you very much again sir

**Comment by wojtek-krysiak** [comment]
admin does not generate id. mongoose should do this. can you paste:

* schema
* full stack trace (where it happens in AdminBro)

**Comment by wojtek-krysiak** [comment]
closing due to lack of communication
