### ISSUE TITLE
Upload image problem after Deployment

### ISSUE THREAD

**Issue by AmiXDev** [SoftwareBrothers/admin-bro#605]
Hello dear Krysiak,

I have watched the upload image functionality video on Youtube a while ago and implemented which it works nice locally. but after deployment I get error for all edit and list components that I have provided. 
the following pictures are the errors that I get in console log

<img width="1005" alt="Screen Shot 1399-06-25 at 15 05 25" src="https://user-images.githubusercontent.com/37555186/93200994-ca89af80-f765-11ea-9125-d4d62ef775ab.png">

<img width="1054" alt="Screen Shot 1399-06-25 at 12 24 14" src="https://user-images.githubusercontent.com/37555186/93201056-e2f9ca00-f765-11ea-8829-ac2559c27692.png">

"admin-bro": "^2.2.4",
"admin-bro-expressjs": "^2.0.5",
"admin-bro-mongoose": "^0.5.0",

Would be immensely grateful for any assistance.

**Comment by AmiXDev** [comment]
I think I could find the problem

component.bundle.js respondes with a status of 500  ❗ ❗ ❗ ❗ ❗ 

<img width="1438" alt="Screen Shot 1399-06-25 at 16 33 12" src="https://user-images.githubusercontent.com/37555186/93208005-1d1c9900-f771-11ea-9b8b-8b56e75c7538.png">

**Comment by wojtek-krysiak** [comment]
in NODE_ENV=production (assume that this is your env setting after deployment), on run, admin tries to bundle components.bundle.js and write to `.adminbro/bundle.js`. Apparently this failed.

In order to debug this run admin locally in NODE_ENV set to production (remember after the run you will have to delete cached .adminro folder). You should see errors.

If not maybe you don't have access to write files in production. Then the simplest solution would be to simply bundle files before the deployment and add them to the repo.

**Comment by wojtek-krysiak** [comment]
PS: you can also use @admin-bro/upload feature which works with the latest version: https://itnext.io/the-easiest-and-fastest-way-to-upload-files-in-node-js-4b49e0123190

**Comment by AmiXDev** [comment]
thanks, you're right I just change development to production in my NODE_ENV and now it works fine.
