### ISSUE TITLE
Fetch additional attributes in show's "after" hook

### ISSUE THREAD

**Issue by m-nazmi** [SoftwareBrothers/admin-bro#625]
According to your documentation in that [link](https://adminbro.com/Action.html#after), you have stated that "after" can be used to fetch additional data after the original handler is being performed. Sorrowfully, if that additional attribute is an array of references, I receive the following error.

`Error: Objects are not valid as a React child (found: object with keys {users, _id, match, title, createdAt, updatedAt}). If you meant to render a collection of children, use an array instead. in DefaultPropertyValue (created by Show$2) in div (created by styled.div) in styled.div (created by Show$2) in Show$2 (created by BasePropertyComponent) in section (created by styled.section) in styled.section (created by BasePropertyComponent) in ErrorBoundary (created by BasePropertyComponent) in BasePropertyComponent (created by Show$8) in section (created by styled.section) in styled.section (created by Show$8) in Show$8 (created by BaseActionComponent) in ErrorBoundary (created by BaseActionComponent) in BaseActionComponent (created by RecordAction) in section (created by wrapper__StyledWrapper) in wrapper__StyledWrapper (created by Wrapper$1) in Wrapper$1 (created by RecordAction) in RecordAction (created by Context.Consumer) in Route (created by App) in Switch (created by App) in section (created by styled.section) in styled.section (created by App) in section (created by styled.section) in styled.section (created by App) in App in Router (created by BrowserRouter) in BrowserRouter in ThemeProvider in Provider
See development console for more details...`

Finally, I want to complain about your documentation because it does not state the whole capabilities of your product! It gives short examples and for the simplest cases.

**Comment by wojtek-krysiak** [comment]
Hi, @m-nazmi - yes you are right regarding the documentation. Product is much bigger than the documentation describes. We try our best to update it and It is still work in progress (btw here is the latest beta documentation. In the same time, we are looking for any contributors willing to help us with that, so if you like you can participate you can:

1. write / update tutorial
2. fix JSDoc in source code

Everything in a regular Pull Requests to either admin-bro repo or admin-bro-dev (there are src for tutorials: https://github.com/SoftwareBrothers/admin-bro-dev/tree/master/docs-src). Also - anyone how reads this issue - you know what to do :)

Regarding the error you have I would need more information. Basically, you have to return `originalResponse` from the function. Because adminbro actions depends on the data inside inside (i..e list depends that in the response there will be a list of records: Array<RecordJSON>. So what you can do is to add additional properties to the response.

I've created recently 3 casts about basic things in admin bro as password hasing and file upload - they in http://jscasts.tv/ (3 last screencasts. You check them out to see how to change the response in before/after hooks
